# **Dataset Information**

The dataset used in this project is downloaded from **Kaggle**. You can find the dataset [here](https://www.kaggle.com/datasets/abdallahwagih/telco-customer-churn?select=Telco_customer_churn.xlsx).

### **Dataset Overview**
This dataset contains detailed information about telecom customers in the United States, including their demographic details, subscription plans, and churn status. The data was collected to help identify the key factors contributing to customer churn, which occurs when customers cancel their services.

### **Key Attributes**
- **Customer Demographics**: Includes gender, city, state, zip code, and geographic coordinates (latitude and longitude).
- **Subscription Information**: This includes details about the customer's contract type (month-to-month, one-year, two-year), payment method (electronic check, mailed check, credit card, etc.), and monthly charges.
- **Churn Data**: Indicates whether the customer has churned (Yes/No), along with a score predicting their likelihood to churn, reasons for leaving, and the customer lifetime value (CLTV).
- **Churn Reasons**: Specific reasons for churn are included, such as competitors offering better deals, service dissatisfaction, or moving to a new location.

### **Key Columns**
- **CustomerID**: Unique identifier for each customer.
- **Gender**: Gender of the customer.
- **Contract**: The contract type (Month-to-month, One year, etc.).
- **Payment Method**: How the customer makes payments (e.g., Bank transfer, Credit card).
- **Monthly Charges**: The amount the customer is billed monthly.
- **Total Charges**: Cumulative amount billed to the customer.
- **Churn Label**: Indicates whether the customer has churned (Yes/No).
- **Churn Reason**: Reason why the customer churned.
  
### **Dataset Uses**
This dataset can be used for various machine learning tasks, including:
- **Customer Churn Prediction**: Identify patterns in customer behavior that signal their likelihood of churning.
- **Customer Segmentation**: Group customers based on their demographics, subscription plans, or payment behavior.
- **Churn Reason Analysis**: Understand the main reasons customers are leaving and build strategies to reduce churn.

### **Dataset Highlights**
- 33 features capturing various aspects of customer demographics, payment behavior, and churn data.
- Rich churn data with reasons for churn, which can help develop insights into customer retention strategies.
- Geospatial information, including customer locations (latitude, longitude), which can be useful for regional analysis of churn.

# **Dataset Loading**

In [1]:
import pandas as pd

df = pd.read_excel("Telco_customer_churn.xlsx")

### Top five rows

In [2]:
df.head()

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,Month-to-month,Yes,Electronic check,99.65,820.5,Yes,1,86,5372,Moved
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes,1,89,5340,Competitor had better devices

### Bottom five rows

In [3]:
df.tail()

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
7038,2569-WGERO,1,United States,California,Landers,92285,"34.341737, -116.539416",34.341737,-116.539416,Female,...,Two year,Yes,Bank transfer (automatic),21.15,1419.4,No,0,45,5306,NaN
7039,6840-RESVB,1,United States,California,Adelanto,92301,"34.667815, -117.536183",34.667815,-117.536183,Male,...,One year,Yes,Mailed check,84.80,1990.5,No,0,59,2140,NaN
7040,2234-XADUH,1,United States,California,Amboy,92304,"34.559882, -115.637164",34.559882,-115.637164,Female,...,One year,Yes,Credit card (automatic),103.20,7362.9,No,0,71,5560,NaN
7041,4801-JZAZL,1,United States,California,Angelus Oaks,92305,"34.1678, -116.86433",34.167800,-116.864330,Female,...,Month-to-month,Yes,Electronic check,29.60,346.45,No,0,59,2793,NaN
7042,3186-AJIEK,1,United States,California,Apple Valley,92308,"34.424926, -117.184503",34.424926,-117.184503,Male,...,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No,0,38,5097,NaN

In [4]:
df.sample(5)

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
5567,0708-SJDIS,1,United States,California,West Hollywood,90069,"34.093781, -118.381061",34.093781,-118.381061,Female,...,Month-to-month,No,Mailed check,65.00,2157.5,No,0,55,5567,NaN
6737,1074-WVEVG,1,United States,California,Los Angeles,90021,"34.029043, -118.239504",34.029043,-118.239504,Female,...,One year,No,Mailed check,20.35,1267,No,0,57,5757,NaN
6175,0281-CNTZX,1,United States,California,Pescadero,94060,"37.22565, -122.297533",37.225650,-122.297533,Male,...,Two year,Yes,Bank transfer (automatic),19.95,1234.8,No,0,74,5151,NaN
7000,6633-SYEUS,1,United States,California,San Diego,92127,"33.017518, -117.118456",33.017518,-117.118456,Female,...,Month-to-month,No,Bank transfer (automatic),83.20,2032.3,No,0,28,2061,NaN
6202,0383-CLDDA,1,United States,California,Stanford,94305,"37.424342, -122.165641",37.424342,-122.165641,Female,...,Two year,Yes,Credit card (automatic),85.35,5897.4,No,0,37,6499,NaN

> We have analyzed the dataset.
on the next files, we will continue with the exploratory data analysis.

+ => [Exploratory Data Analysis (EDA)](https://github.com/MOHSIN184/Telecom_Churn_Prediction/blob/main/3.%20EDA.ipynb)